import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const cormorantGaramond = Cormorant_Garamond({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cormorant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/hlogo3.svg",
    shortcut: "/hlogo.svg",
    apple: "/hlogo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Hero Images */}
        <link rel="preload" as="image" href="/home/hero.webp" />
        <link rel="preload" as="image" href="/about/hero.webp" />
        <link rel="preload" as="image" href="/completed-projects/hero.webp" />
        <link rel="preload" as="image" href="/contact/hero.webp" />
        <link rel="preload" as="image" href="/home/Elixir-Akkara-Gardens1.webp" />
        <link rel="preload" as="image" href="/projects/Elixir-Anfeild.webp" />
        <link rel="preload" as="image" href="/projects/Elixir-Manavath-Heights1.webp" />
        <link rel="preload" as="image" href="/home/Elixir-Super-Luxury-Villas11.webp" />
        <link rel="preload" as="image" href="/gallery/hero.webp" />
        <link rel="preload" as="image" href="/blog/hero.webp" />
        <link rel="preload" as="image" href="/home/Orchid1.webp" />
        <link rel="preload" as="image" href="/projects/hero.webp" />
        <link rel="preload" as="image" href="/testimonial/hero.webp" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${cormorantGaramond.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />

        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
